### ISSUE TITLE
Improvement 

### ISSUE THREAD

**Issue by AbhishekSoni2001** [vritika09/Browser-Support-Calculator#1]
hi,
I have seen you code & I think there can  be some improvement in your code like,

- useless LINK which slows down your website
- Invalid id declaration as id has a same name  in your code
- result display should be editable as user might want to directly write command in that window
- maximum input limit should be managed
- while in error condition , if equal key pressed twice, it shows an invalid error & it can be managed be alert command & reset display equal=NULL

![UI](https://user-images.githubusercontent.com/74598578/119100512-a6d5e200-ba35-11eb-9ca0-48463c143d8d.PNG)
![When Equal Pressend in error](https://user-images.githubusercontent.com/74598578/119100516-a8070f00-ba35-11eb-9acd-d3b6f7e6b841.PNG)

INDEX.html (Improved)

<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <link rel="stylesheet" href="calsi.css">
        <title>Calculator</title>
    </head>
    <body>  
        <div class="grid-container">
            <div class="display" ><input id="d" maxlength="12" value="0"></div>
            <br>
            <div class="keys">

                <button  onclick='v("7")'>7</button>
                <button  onclick='v("8")'>8</button>
                <button  onclick='v("9")'>9</button>
                <button  class="op" onclick='v("+")'>+</button>
                <br><br>
                <button  onclick='v("4")'>4</button>
                <button  onclick='v("5")'>5</button>
                <button  onclick='v("6")'>6</button>
                <button  class="op" onclick='v("-")'>-</button>
                <br><br>
                <button onclick='v("1")'>1</button>
                <button  onclick='v("2")'>2</button>
                <button  onclick='v("3")'>3</button>
                <button  class="op" onclick='v("*")'>x</button>
                <br><br>
                <button  class="c" onclick='c("")'>C</button>
                <button  onclick='v("0")'>0</button>
                <button  class="op" onclick='e("=")'>=</button>
                <button  class="op" onclick='v("/")'>/</button>
                <br><br>
            </div>
        </div>
        <script>
            function c(val)
            {
                document.getElementById("d").value = val;
            }
            function v(val)
            {
                document.getElementById("d").value += val;
            }
            function e()
            {
                try
                {
                    c(eval(document.getElementById("d").value));
                } catch (e)
                {
                    alert("Error");  // Display a Alert which is better.
                    c(' '); // reset display to NULL                
                }
            }
        </script>
    </body>
</html>

CSS(Improved)

body
{
    background: #2196F3;
}
.grid-container{
    background-color: lightskyblue;
    text-align: center;
    padding: 20px;
    font-size: 30px;
    position: relative;
    height: 500px;
    width: 500px;
    border-radius: 30px;
    margin: auto;
    display: block;
    margin-top: 3%;  
    text-align: center;
    border: 2px solid black;
    cursor: pointer;
}

button{
    text-decoration: none;
    width: 40px;
    height: 40px;
    padding: 30px;    
    font-weight: bold;
    font-size:  100%;
    text-align: center; 
}

.display input{
    background-color: white;
    color: black;
    border-radius: 20px;  
    width: 100%;
    height: 50px;
    left: 2px;
    top: 2px;
    font-size: 25px;
    text-align: right;  
}

.keys button {
    text-align: center;
    border: 2px double black;
    border-radius: 50%;
    padding: 35px;
}

button:hover{
    background-color: lightcoral;
    color: black;
}

.c{
    background-color: red;
    color: black;
}

.op{
    background-color: rgba(0, 0, 0, 0.842);
    color: white;    
}

#d{
    border:  5px solid black;
    padding: 0px;
    resize: horizontal;
}

**Comment by vritika09** [comment]
Okay thanks
